properties([
  parameters([
    [$class: 'GitParameterDefinition',
      name: 'BRANCH',
      type: 'PT_BRANCH',
      defaultValue: 'origin/master',
      description: 'Choose your GitHub branch',
      branchFilter: '.*',
      tagFilter: '*',
      sortMode: 'NONE',
      selectedValue: 'DEFAULT',
      quickFilterEnabled: true
    ]
  ])
])
pipeline {
  agent any

  environment {
    PROCESS_MINER_VIEWER_GIT_URL = credentials('PROCESS_MINER_VIEWER_GIT_URL')
  }

  options {
    buildDiscarder(logRotator(numToKeepStr: '30', artifactNumToKeepStr: '5'))
  }

  triggers {
    cron '@midnight'
  }

  parameters {
    string(name: 'engineSource', defaultValue: 'https://developer.axonivy.com/permalink/13.1.0/axonivy-engine.zip', description: 'Engine page url')
  }

  stages {
    stage('Set Display Name') {
      steps {
        script {
          def userId = currentBuild.getBuildCauses('hudson.model.Cause$UserIdCause')[0]?.userId
          def fullName = "system"
          if (userId) {
            def user = jenkins.model.Jenkins.instance.getUser(userId)
            fullName = user?.getDisplayName() ?: userId
          }
          currentBuild.displayName = "Build #${env.BUILD_NUMBER} on branch ${BRANCH} - trigger by ${fullName}"
        }
      }
    }

    stage('Checkout Source') {
      steps {
        script {
          def gitBranch = params.BRANCH.replaceFirst(/^origin\//, '')
          git branch: gitBranch, url: env.PROCESS_MINER_VIEWER_GIT_URL
        }
      }
    }
    stage('Build') {
      steps {
        script {
          catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
            docker.build('node', '-f .build/Dockerfile.node .').inside('--user 0') {
              sh 'npm install --unsafe-perm'
              sh 'npm run ci'
            }
          }
          archiveArtifacts artifacts: 'dist/**', allowEmptyArchive: true
          archiveArtifacts artifacts: 'eslint.xml', allowEmptyArchive: true
        }
      }
    }
    stage('Integration Tests') {
      steps {
        script {
          catchError(buildResult: 'UNSTABLE', stageResult: 'UNSTABLE') {
            docker.build('node-webtest', '-f .build/Dockerfile.playwright .').inside('--user 0') {
              dir('tests/miner-test-project') {
                maven cmd: "-ntp verify -Dengine.page.url=${params.engineSource}"
              }
            }
          }
          archiveArtifacts artifacts: 'test-results/**', allowEmptyArchive: true
        }
      }
    }
  }
}